// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdorbjtcaictzcabmxyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impkb3JianRjYWljdHpjYWJteHliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkwMDA0NTksImV4cCI6MjA5NDU3NjQ1OX0.JlQCqFiLY8BUhfUaa4KUlSxEhKLH5voqg_ag3Z9tbnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});