// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txtmxkhgnfqpudzdmict.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4dG14a2hnbmZxcHVkemRtaWN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg5NzQ1NTgsImV4cCI6MjA5NDU1MDU1OH0.0bjJqxXhCGVBBRb7JdyGn1I194tl12mf0rnUBCgya-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});